pipeline {

  
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::300374333822:role/jenkins-irsa-role
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/my-custom-kubectl:1.3
      command: ["cat"]
      tty: true
"""
    }
  }


  options {
    skipDefaultCheckout()
  }


  stages {
    stage('Trigger Upstreams Builds ') {
      parallel {
        stage('Upstream 1') {
          steps {
            build job: 'real-job-name-1', wait: true
          }
        }
        stage('Upstream 2') {
          steps {
            build job: 'real-job-name-2', wait: true
          }
        }
        stage('Upstream 3') {
          steps {
            build job: 'real-job-name-3', wait: true
          }
        }
      }
    }

    stage('Continue PoC') {
      steps {
        echo '✅ All upstream jobs done. Proceeding with PoC...'
      }
    }
  }
}


/*
This Jenkinsfile is designed to trigger multiple upstream jobs in parallel.
Each upstream job is executed in its own stage, allowing for concurrent execution.
And the Wait option is set to true, ensuring that the pipeline waits for each upstream job to complete before proceeding.
This is useful for scenarios where you have multiple independent jobs that can run simultaneously, improving overall pipeline efficiency.
After all upstream jobs are completed, the pipeline proceeds to the next stage, which can be used for further processing or deployment steps.
This structure allows for a clear and organized approach to managing multiple upstream jobs within a single pipeline, making it easier to maintain and understand the flow of the CI/CD process.
*/