pipeline {

  
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-efs-agent
  labels:
    jenkins: agent
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-4
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace
    - name: runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/my-custom-kubectl:1.3
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace
  volumes:
    - name: efs-workspace
      persistentVolumeClaim:
        claimName: jenkins-efs-pvc
"""
    }
  }


  environment {
    BUILD_REPO_URL = 'https://github.com/pablo-inchausti-caylent/liferay-portal.git'
    BUILD_TEST_BRANCH   = 'master-ci-6005-downstream-builds'

    AWS_ACCOUNT_ID='300374333822'
    AWS_REGION='us-east-2'

    // DOWNSTREAM_BUILD_ID = "${env.BUILD_ID}"
    DOWNSTREAM_BUILD_ID='downstream-build-1'

    AWS_S3_BUCKET='liferayci-file-propagator-mvp'
    AWS_S3_PATH='build'

    AWS_S3_URL_ARTIFACTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/artifacts"
    AWS_S3_URL_TESTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/tests"

    BUILD_BUNDLE_NAME='liferay-portal-bundle-tomcat.tar.gz'
    BUILD_SOURCE_NAME='liferay-portal-source.tar.gz'

    BUILD_BUNDLE_DUMMY_NAME="dummy-${BUILD_BUNDLE_NAME}"
    BUILD_SOURCE_DUMMY_NAME="dummy-${BUILD_SOURCE_NAME}"

    TEST_DUMMY_NAME="test-${DOWNSTREAM_BUILD_ID}-dummy.xml"

    // s3://liferayci-file-propagator-mvp/build/35/artifacts
    // s3://liferayci-file-propagator-mvp/build/35/tests

    // liferay-portal-bundle-tomcat.tar.gz  (~1.7gb)
    // liferay-portal-source.tar.gz         (~1.2gb) 
  }

  options {
    skipDefaultCheckout()
  }


  stages {

    stage('Prepare') {
      steps {
        script {
          echo "🚀 Starting ${DOWNSTREAM_BUILD_ID}"
          // Print some common Jenkins env vars
          echo "Branch: ${env.BRANCH_NAME}"
          echo "Job Name: ${env.JOB_NAME}"
          echo "Build Number: ${env.BUILD_NUMBER}"
          echo "Workspace: ${env.WORKSPACE}"
          echo "Git Commit: ${env.GIT_COMMIT}"

          echo "AWS s3 ARTIFACTS URL: ${env.AWS_S3_URL_ARTIFACTS}"
          echo "AWS s3 TEST URL: ${env.AWS_S3_URL_TESTS}"
        }
      }
    }

    stage('Branch Guard') {
      when {
        expression {
          // Skip this job if it's NOT on the expected branch
          if (env.BRANCH_NAME != {env.BUILD_TEST_BRANCH}) {
            echo "Skipped: This job only runs on 'master-ci-6005-downstream-builds'. Current: ${env.BRANCH_NAME}"
            return false
          }
          return true
        }
      }
      steps {
        echo "Correct branch detected: ${env.BRANCH_NAME}"
      }
    }

    stage('Checkout Shallow') {
      steps {
        echo "🔨 Simulating Checkout Shallow ${DOWNSTREAM_BUILD_ID}"

        // container('runner') {
        //   checkout([
        //     $class: 'GitSCM',
        //     branches: [[name: "*/${env.BUILD_TEST_BRANCH}"]],
        //     userRemoteConfigs: [[
        //       url: "${env.GIT_REPO_URL}",
        //       credentialsId: 'github-pat-pei'
        //     ]],
        //     extensions: [
        //       [$class: 'CloneOption', shallow: true, depth: 1, noTags: false, reference: '', timeout: 10]
        //     ]
        //   ])
        // }
      }
    }

    stage('Reading bundle from EFS') {
      steps {
        container('runner') {
          sh """
            ls -al
            df -h
            echo "🔍 Checking EFS mount at /home/jenkins/agent"
            mount | grep /home/jenkins/agent || echo "❌ EFS NOT mounted"

            ls -al /home/jenkins/agent

            echo "📄 Reading test file from EFS..."
            cat /home/jenkins/agent/${BUILD_SOURCE_DUMMY_NAME} || echo "❌ Test file not found"

            echo "📄 Writing test file to EFS..."
            date > /home/jenkins/agent/test-efs-bundle-${DOWNSTREAM_BUILD_ID}.txt
          """
        }
      }
    }

    stage('Build') {
      steps {
        echo "🔨 Simulating build in ${DOWNSTREAM_BUILD_ID}"
        sh 'sleep 5'
      }
    }


    stage('Upload to S3 - Test') {

      steps {
        container('runner') {
          sh """
            echo "📤 Uploading tests to S3..."
            aws s3 cp /home/jenkins/agent/${TEST_DUMMY_NAME} \
                  ${env.AWS_S3_URL_TESTS}/${TEST_DUMMY_NAME} || echo "❌ Upload failed"
          """
        }
      }
    }


    stage('Complete') {
      steps {
        echo "✅ ${DOWNSTREAM_BUILD_ID} completed successfully!"
      }
    }
  }
  
}