pipeline {
  agent {
    kubernetes {
      yaml """
      apiVersion: v1
      kind: Pod
      spec:
        containers:
        - name: busybox
          image: busybox
          command:
          - sleep
          args:
          - "60"
      """
    }
  }
  stages {
    stage('Test') {
      steps {
        container('busybox') {
          sh 'echo Hello from agent && sleep 30'
        }
      }
    }
  }
}

