pipeline {

  agent {
    kubernetes {
      yaml """
  apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::300374333822:role/jenkins-irsa-role
  spec:
    containers:
      - name: runner
        image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/my-custom-kubectl:1.3
        command: [ "cat" ]
        tty: true
  """
    }
  }

  environment {
    GIT_REPO_URL = 'https://github.com/pablo-inchausti-caylent/liferay-portal.git'
    GIT_BRANCH   = 'master-ci-6005-postgresql'

    AWS_ACCOUNT_ID='300374333822'
    AWS_REGION='us-east-2'

    COMPOSE_FILE = '02-docker-compose.yaml'

  }

  options {
    skipDefaultCheckout()
  }

  stages {


    stage('Install AWS CLI and Test IRSA (optional) ') {
      steps {
        container('runner') {
          echo '📦 Installing AWS CLI  (if needed)...'
          sh '''
            aws --version || true 
            aws sts get-caller-identity || echo "❌ AWS CLI not configured or IRSA not working"
            aws s3 ls || echo "❌ AWS CLI S3 (IRSA) access not working"
          '''
        }
      }
    }


    stage('Install Docker ') {
      steps {
        container('runner') {
          echo '📦 Installing Docker  (if needed)...'
          sh '''
              kubectl -version || true
              docker-compose --version || true
              docker --version || true
          '''
        }
      }
    }



    stage('ECR Login') {
      steps {
        container('runner') {
            sh '''
              aws ecr get-login-password --region "$AWS_REGION" | \
                docker login --username AWS \
                        --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
            ''' 
        }
      }
    }




    


  }



}


/*
This Jenkinsfile uses a Kubernetes agent to run the pipeline steps.

with a custom Docker image that includes kubectl as runner.
300374333822.dkr.ecr.us-east-2.amazonaws.com/my-custom-kubectl:1.1


It includes stages for installing AWS CLI, Docker, and logging into AWS ECR.
The environment variables are set for the Git repository, AWS account, and region.

*/