pipeline {

  
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::300374333822:role/jenkins-irsa-role
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/my-custom-kubectl:1.3
      command: ["cat"]
      tty: true
"""
    }
  }


  options {
    skipDefaultCheckout()
  }


  stages {
    stage('Prepare') {
      steps {
        echo '🚀 Starting upstream-job-2'
      }
    }

    stage('Build') {
      steps {
        echo '🔨 Simulating build in upstream-job-2...'
        sh 'sleep 5'
      }
    }

    stage('Complete') {
      steps {
        echo '✅ upstream-job-2 completed successfully!'
      }
    }
  }
  
}