---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
        - name: runner
          image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
          command: ["/bin/bash"]
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: test1
          image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
          command: ["/bin/bash"]
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
        - name: test2
          image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
          command: ["/bin/bash"]
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        app: test3
    spec:
      containers:
        - name: test3
          image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
          command: ["/bin/bash"]
          tty: true
---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql
spec:
  containers:
    - name: postgresql
      image: postgres:16.3-bullseye
      env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
      tty: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:8.4.4
      command:
        - "--character-set-server=utf8"
        - "--connect_timeout=120"
        - "--max_allowed_packet=104857600"
        - "--wait_timeout=1200"
        - "--tls-version=TLSv1.2"
      env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
      securityContext:
        privileged: true
      tty: true

# Prior to add namespaces
# I didn't test it