apiVersion: v1
kind: Pod
metadata:
  name: liferay-runner-pod
  namespace: liferay-jenkins
  labels:
    app: liferay-runner
spec:
  containers:
    - name: runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
      tty: true
      command: ["/bin/bash"]
    - name: test1
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
      tty: true
      command: ["/bin/bash"]
    - name: test2
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
      tty: true
      command: ["/bin/bash"]
    - name: test3
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:1.0.1
      tty: true
      command: ["/bin/bash"]
    - name: postgresql
      image: postgres:16.3-bullseye
      tty: true
      env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
    - name: mysql
      image: mysql:8.4.4
      tty: true
      env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
      args:
        - "--character-set-server=utf8"
        - "--connect_timeout=120"
        - "--max_allowed_packet=104857600"
        - "--wait_timeout=1200"
        - "--tls-version=TLSv1.2"

  restartPolicy: Never

