pipeline {

  
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-efs-agent
  securityContext:
    fsGroup: 1000
  labels:
    jenkins: agent
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-4
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace


    - name: runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-caylent-runner:2.0.2-keys
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace
        - mountPath: /home/jenkins/local
          name: workspace-volume


    - name: postgresql
      image: postgres:16.3-bullseye
      env:
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
      tty: true


  volumes:
    - name: efs-workspace
      persistentVolumeClaim:
        claimName: jenkins-efs-pvc
    - name: workspace-volume
      emptyDir: {}
"""
    }
  }


  environment {
    BUILD_REPO_URL = 'https://github.com/pablo-inchausti-caylent/liferay-portal.git'
    BUILD_TEST_BRANCH   = 'master-ci-6005-downstream-builds'

    AWS_ACCOUNT_ID='300374333822'
    AWS_REGION='us-east-2'

    DOWNSTREAM_BUILD_ID='downstream-build-3'

    AWS_S3_BUCKET='liferayci-file-propagator-mvp'
    AWS_S3_PATH='build'

    AWS_S3_URL_ARTIFACTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/artifacts"
    AWS_S3_URL_TESTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/tests"

    BUILD_BUNDLE_NAME='liferay-portal-bundle-tomcat.tar.gz'
    BUILD_SOURCE_NAME='liferay-portal-source.tar.gz'

    DOWNSTREAM_BUILD_NUMBER = "${env.BUILD_NUMBER}"
    
    LOCAL_DIR_CHECKOUT  = "/opt/dev/projects/github"

    DEFAULT_BUILD_NUMBER = 1
    TARBALL_GIT_NAME     = "liferay-portal-repo-${DEFAULT_BUILD_NUMBER}.tar.gz"
    TARBALL_GIT_REPO     = "/home/jenkins/local/${TARBALL_GIT_NAME}"

    DEFAULT_LIFERAY_ARTIFACT_FOLDER = "/home/jenkins/agent/liferay-artifacts/build-${DEFAULT_BUILD_NUMBER}"
  }




  parameters {
    string(name: 'PARENT_BUILD_NUMBER')
    string(name: 'PARENT_GIT_COMMIT')
    string(name: 'TARBALL_GIT_NAME',             defaultValue: "${env.TARBALL_GIT_NAME}")
    string(name: 'TARBALL_GIT_REPO',             defaultValue: "${env.TARBALL_GIT_REPO}")
    string(name: 'EFS_MOUNT_PATH',               defaultValue: "/home/jenkins/agent")
    string(name: 'EFS_LIFERAY_ARTIFACT_FOLDER',  defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}")
    string(name: 'EFS_LIFERAY_ARTIFACT_REPOS',   defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}/repo-github")
    string(name: 'EFS_LIFERAY_ARTIFACT_BUNDLES', defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}/bundles")
    string(name: 'EFS_LIFERAY_ARTIFACT_TEST',    defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}/tests")
  }

  options {
    skipDefaultCheckout()
  }


  stages {

    stage('Prepare') {
      steps {
        script {
          echo "🚀 Starting ${DOWNSTREAM_BUILD_ID}"
          // Print some common Jenkins env vars
          echo "Branch: ${env.BRANCH_NAME}"
          echo "Job Name: ${env.JOB_NAME}"
          echo "Build Number: ${env.BUILD_NUMBER}"
          echo "Workspace: ${env.WORKSPACE}"
          echo "Git Commit: ${env.GIT_COMMIT}"

          echo "AWS s3 ARTIFACTS URL: ${env.AWS_S3_URL_ARTIFACTS}"
          echo "AWS s3 TEST URL: ${env.AWS_S3_URL_TESTS}"

          echo "PARAMETERS: "
          echo "  PARENT_BUILD_NUMBER: ${params.PARENT_BUILD_NUMBER}"
          echo "  PARENT_GIT_COMMIT: ${params.PARENT_GIT_COMMIT}"
          echo "  TARBALL_GIT_NAME: ${params.TARBALL_GIT_NAME}"
          echo "  TARBALL_GIT_REPO: ${params.TARBALL_GIT_REPO}"
          echo "  EFS_MOUNT_PATH: ${params.EFS_MOUNT_PATH}"
          echo "  EFS_LIFERAY_ARTIFACT_FOLDER: ${params.EFS_LIFERAY_ARTIFACT_FOLDER}"
          echo "  EFS_LIFERAY_ARTIFACT_REPOS: ${params.EFS_LIFERAY_ARTIFACT_REPOS}"
          echo "  EFS_LIFERAY_ARTIFACT_BUNDLES: ${params.EFS_LIFERAY_ARTIFACT_BUNDLES}"
          echo "  EFS_LIFERAY_ARTIFACT_TEST: ${params.EFS_LIFERAY_ARTIFACT_TEST}" 


          env.TARBALL_GIT_NAME     = "liferay-portal-repo-${params.PARENT_BUILD_NUMBER}.tar.gz"
          env.DEFAULT_LIFERAY_ARTIFACT_FOLDER = "/home/jenkins/agent/liferay-artifacts/build-${env.DEFAULT_BUILD_NUMBER}"

          echo "kubectl exec -it ${env.NODE_NAME} -c runner -n liferay-jenkins -- bash"

          echo "  env.TARBALL_GIT_NAME: ${env.TARBALL_GIT_NAME}"
          echo "  env.DEFAULT_LIFERAY_ARTIFACT_FOLDER: ${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}"
          echo "      TARBALL_GIT_NAME: ${TARBALL_GIT_NAME}"
          
          MY_NEW_TARBALL_GIT_NAME     = "liferay-portal-repo-${params.PARENT_BUILD_NUMBER}.tar.gz"
          
          echo " MY_NEW_TARBALL_GIT_NAME: ${MY_NEW_TARBALL_GIT_NAME}"


        }
      }
    }


    stage('Source Code Copy') {
      steps {
        container('runner') {

          script {            

            echo " MY_NEW_TARBALL_GIT_NAME: ${MY_NEW_TARBALL_GIT_NAME}"
            echo " MY_NEW_TARBALL_GIT_NAME: ${MY_NEW_TARBALL_GIT_NAME}"
            
            MY_NEW_TARBALL_GIT_NAME     = "liferay-portal-repo-${params.PARENT_BUILD_NUMBER}.tar.gz"
            MY_NEW_DEFAULT_LIFERAY_ARTIFACT_FOLDER = "/home/jenkins/agent/liferay-artifacts/build-${params.PARENT_BUILD_NUMBER}"

            echo "  MY_NEW_TARBALL_GIT_NAME: ${MY_NEW_TARBALL_GIT_NAME}"
            echo "  MY_NEW_DEFAULT_LIFERAY_ARTIFACT_FOLDER: ${MY_NEW_DEFAULT_LIFERAY_ARTIFACT_FOLDER}"

          }


          sh """
  
            #----------------
            # Clean the Local directory 
            echo '🧹 Version 4.1..'
            echo '🧹 Cleaning checkout folder...'
            rm -rf ${LOCAL_DIR_CHECKOUT} && mkdir -p ${LOCAL_DIR_CHECKOUT}


            # Copy bundle at local
    
            cp ${MY_NEW_DEFAULT_LIFERAY_ARTIFACT_FOLDER}/repo-github/${MY_NEW_TARBALL_GIT_NAME} ${LOCAL_DIR_CHECKOUT}
            echo "  EFS_LIFERAY_ARTIFACT_BUNDLES: ${MY_NEW_DEFAULT_LIFERAY_ARTIFACT_FOLDER}/repo-github/"${MY_NEW_TARBALL_GIT_NAME} ${LOCAL_DIR_CHECKOUT}

            ls -al ${LOCAL_DIR_CHECKOUT}
            echo '📦 Extracting tarball (with pigz)...'
            tar         -xzf ${LOCAL_DIR_CHECKOUT}/${MY_NEW_TARBALL_GIT_NAME} -C ${LOCAL_DIR_CHECKOUT}

            #----------------
            echo '📂 Extracted contents:  '
            ls -al ${LOCAL_DIR_CHECKOUT}
            echo '📂 Checking out source code (emulated) done...'
            rm -f ${LOCAL_DIR_CHECKOUT}/${MY_NEW_TARBALL_GIT_NAME}
            echo '📂 Source code ready in ${LOCAL_DIR_CHECKOUT}'
            
          """

        }
      }
    }

  

  stage('Unit Test Setup') {
      steps {
        container('runner') {
            script {
                sh """
                  echo '📥 Build the Bundle - Step 0 ... '
                  echo "📂 LOCAL_DIR_CHECKOUT: ${LOCAL_DIR_CHECKOUT}  "   
                  ls -a
                  pwd     

                  cd /opt/dev/projects/github/liferay-portal



                  echo "app.server.parent.dir=/opt/dev/projects/github/liferay-portal/bundles" > app.server.\$HOSTNAME.properties

                  echo "liferay.home=/opt/dev/projects/github/liferay-portal/bundles" > build.\$HOSTNAME.properties
                  echo "mirrors.hostname=" >> build.\$HOSTNAME.properties
                  
                  #
                  # NOTE: These properties are variable between different testing environments
                  #

                  echo "java.jdk.default.runtime.version=jdk21" > test.\$HOSTNAME.properties
                  echo "database.type=postgresql" >> test.\$HOSTNAME.properties
                  echo "database.postgresql.host=postgresql" >> test.\$HOSTNAME.properties
                  echo "database.postgresql.username=root" >> test.\$HOSTNAME.properties
                  echo "database.postgresql.password=liferay123" >> test.\$HOSTNAME.properties

                  ant setup-profile-dxp
                  
                  ant -f build-test.xml rebuild-database prepare-portal-ext-properties


                """ 
            }

        }
      }
    }



    stage('Unit Tests') {
      steps {
        container('runner') {

            script {
                sh """
                  echo '📥 Build the Bundle - Step 1 ... '
                  echo "📂 LOCAL_DIR_CHECKOUT: ${LOCAL_DIR_CHECKOUT}  "   
                  ls -a
                  pwd     

                  cd /opt/dev/projects/github/liferay-portal

                  ant -f build-test-batch.xml modules-integration-postgresql163 -Dtest.batch.name=modules-integration-postgresql163 -Daxis.variable=0 -DTEST_CLASS_GROUP_0=com/liferay/jenkins/results/parser/test/DummyIntegrationTest.class
                  
                """ 
            }

        }
      }
    }


    stage(' Upload To S3') {
      steps {
        container('runner') {
          script {
              sh """
                echo '📥 Uploading test results to S3 ... '

                aws s3 cp --no-progress \
                    /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml \
                    s3://liferayci-file-propagator-mvp/builds/test/${params.PARENT_BUILD_NUMBER}/${DOWNSTREAM_BUILD_NUMBER}/TESTS-TestSuites.xml

              """ 
          }
        }
      }
    }

    stage('Complete') {
      steps {
        echo "✅ ${DOWNSTREAM_BUILD_ID} completed successfully!"
      }
    }
  }
  
}