pipeline {

  
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-efs-agent
  securityContext:
    fsGroup: 1000
  labels:
    jenkins: agent
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:3309.v27b_9314fd1a_4-4
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace
    - name: runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-liferay-runner:2.0.1
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace
        - mountPath: /home/jenkins/local
          name: workspace-volume
  volumes:
    - name: efs-workspace
      persistentVolumeClaim:
        claimName: jenkins-efs-pvc
    - name: workspace-volume
      emptyDir: {}
"""
    }
  }


  environment {
    BUILD_REPO_URL = 'https://github.com/pablo-inchausti-caylent/liferay-portal.git'
    BUILD_TEST_BRANCH   = 'master-ci-6005-downstream-builds'

    AWS_ACCOUNT_ID='300374333822'
    AWS_REGION='us-east-2'

    // DOWNSTREAM_BUILD_ID = "${env.BUILD_ID}"
    DOWNSTREAM_BUILD_ID='downstream-build-3'

    AWS_S3_BUCKET='liferayci-file-propagator-mvp'
    AWS_S3_PATH='build'

    AWS_S3_URL_ARTIFACTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/artifacts"
    AWS_S3_URL_TESTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.BUILD_NUMBER}/tests"

    BUILD_BUNDLE_NAME='liferay-portal-bundle-tomcat.tar.gz'
    BUILD_SOURCE_NAME='liferay-portal-source.tar.gz'

    BUILD_BUNDLE_DUMMY_NAME="dummy-${BUILD_BUNDLE_NAME}"
    BUILD_SOURCE_DUMMY_NAME="dummy-${BUILD_SOURCE_NAME}"

    TEST_DUMMY_NAME="test-${DOWNSTREAM_BUILD_ID}-dummy.xml"

    // s3://liferayci-file-propagator-mvp/build/35/artifacts
    // s3://liferayci-file-propagator-mvp/build/35/tests

    // liferay-portal-bundle-tomcat.tar.gz  (~1.7gb)
    // liferay-portal-source.tar.gz         (~1.2gb) 


    LOCAL_DIR_CHECKOUT  = "/opt/dev/projects/github"

    DEFAULT_BUILD_NUMBER = 1
    TARBALL_GIT_NAME     = "liferay-portal-repo-${DEFAULT_BUILD_NUMBER}.tar.gz"
    TARBALL_GIT_REPO     = "/home/jenkins/local/${TARBALL_GIT_NAME}"

    DEFAULT_LIFERAY_ARTIFACT_FOLDER = "/home/jenkins/agent/liferay-artifacts/build-${DEFAULT_BUILD_NUMBER}"
  }




  parameters {
    string(name: 'PARENT_BUILD_NUMBER')
    string(name: 'PARENT_GIT_COMMIT')
    string(name: 'TARBALL_GIT_NAME',             defaultValue: "${env.TARBALL_GIT_NAME}")
    string(name: 'TARBALL_GIT_REPO',             defaultValue: "${env.TARBALL_GIT_REPO}")
    string(name: 'EFS_MOUNT_PATH',               defaultValue: "/home/jenkins/agent")
    string(name: 'EFS_LIFERAY_ARTIFACT_FOLDER',  defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}")
    string(name: 'EFS_LIFERAY_ARTIFACT_REPOS',   defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}/repo-github")
    string(name: 'EFS_LIFERAY_ARTIFACT_BUNDLES', defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}/bundles")
    string(name: 'EFS_LIFERAY_ARTIFACT_TEST',    defaultValue: "${env.DEFAULT_LIFERAY_ARTIFACT_FOLDER}/tests")
  }

  options {
    skipDefaultCheckout()
  }


  stages {

    stage('Prepare') {
      steps {
        script {
          echo "🚀 Starting ${DOWNSTREAM_BUILD_ID}"
          // Print some common Jenkins env vars
          echo "Branch: ${env.BRANCH_NAME}"
          echo "Job Name: ${env.JOB_NAME}"
          echo "Build Number: ${env.BUILD_NUMBER}"
          echo "Workspace: ${env.WORKSPACE}"
          echo "Git Commit: ${env.GIT_COMMIT}"

          echo "AWS s3 ARTIFACTS URL: ${env.AWS_S3_URL_ARTIFACTS}"
          echo "AWS s3 TEST URL: ${env.AWS_S3_URL_TESTS}"

          echo "PARAMETERS: "
          echo "  PARENT_BUILD_NUMBER: ${params.PARENT_BUILD_NUMBER}"
          echo "  PARENT_GIT_COMMIT: ${params.PARENT_GIT_COMMIT}"
          echo "  TARBALL_GIT_NAME: ${params.TARBALL_GIT_NAME}"
          echo "  TARBALL_GIT_REPO: ${params.TARBALL_GIT_REPO}"
          echo "  EFS_MOUNT_PATH: ${params.EFS_MOUNT_PATH}"
          echo "  EFS_LIFERAY_ARTIFACT_FOLDER: ${params.EFS_LIFERAY_ARTIFACT_FOLDER}"
          echo "  EFS_LIFERAY_ARTIFACT_REPOS: ${params.EFS_LIFERAY_ARTIFACT_REPOS}"
          echo "  EFS_LIFERAY_ARTIFACT_BUNDLES: ${params.EFS_LIFERAY_ARTIFACT_BUNDLES}"
          echo "  EFS_LIFERAY_ARTIFACT_TEST: ${params.EFS_LIFERAY_ARTIFACT_TEST}" 


          env.TARBALL_GIT_NAME     = "liferay-portal-repo-${params.PARENT_BUILD_NUMBER}.tar.gz"
          env.DEFAULT_LIFERAY_ARTIFACT_FOLDER = "/home/jenkins/agent/liferay-artifacts/build-${env.DEFAULT_BUILD_NUMBER}"

        }
      }
    }

    stage('Branch Guard') {
      when {
        expression {
          // Skip this job if it's NOT on the expected branch
          if (env.BRANCH_NAME != {env.BUILD_TEST_BRANCH}) {
            echo "Skipped: This job only runs on 'master-ci-6005-downstream-builds'. Current: ${env.BRANCH_NAME}"
            return false
          }
          return true
        }
      }
      steps {
        echo "Correct branch detected: ${env.BRANCH_NAME}"
      }
    }

    stage('Source Code Receive') {
      steps {
        container('runner') {


          sh """
            # PARAMETERS: 
            #   PARENT_BUILD_NUMBER: 277
            #   PARENT_GIT_COMMIT: 
            # env.TARBALL_GIT_NAME     = "liferay-portal-repo- $ { params.PARENT_BUILD_NUMBER. } .tar.gz"
            #   TARBALL_GIT_NAME:         liferay-portal-repo-1.tar.gz
            #   TARBALL_GIT_REPO: /opt/dev/projects/github/liferay-portal-repo-1.tar.gz
            #   EFS_MOUNT_PATH: /home/jenkins/agent
            #   EFS_LIFERAY_ARTIFACT_FOLDER:   /home/jenkins/agent/liferay-artifacts/build-277
            #   EFS_LIFERAY_ARTIFACT_REPOS:    /home/jenkins/agent/liferay-artifacts/build-277/repo-github
            #   EFS_LIFERAY_ARTIFACT_BUNDLES:  /home/jenkins/agent/liferay-artifacts/build-277/bundles
            #   EFS_LIFERAY_ARTIFACT_TEST:     /home/jenkins/agent/liferay-artifacts/build-277/tests

            # LOCAL_DIR_CHECKOUT  = "/opt/dev/projects/github"
            # /home/jenkins/agent/liferay-artifacts/build-277/bundles/"liferay-portal-repo- $ { params.PARENT_BUILD_NUMBER. } .tar.gz"

          """

          env.TARBALL_GIT_NAME     = "liferay-portal-repo-${params.PARENT_BUILD_NUMBER}.tar.gz"
          env.DEFAULT_LIFERAY_ARTIFACT_FOLDER = "/home/jenkins/agent/liferay-artifacts/build-${env.DEFAULT_BUILD_NUMBER}"


          sh """
  
            #----------------
            # Clean the Local directory 
            echo '🧹 Version 4.1..'
            echo '🧹 Cleaning checkout folder...'
            rm -rf ${LOCAL_DIR_CHECKOUT} && mkdir -p ${LOCAL_DIR_CHECKOUT}


            # Copy bundle at local
    
            cp ${params.EFS_LIFERAY_ARTIFACT_BUNDLES}/${env.TARBALL_GIT_NAME} ${LOCAL_DIR_CHECKOUT}

            ls -al ${LOCAL_DIR_CHECKOUT}
            echo '📦 Extracting tarball (with pigz)...'
            tar         -xzf ${LOCAL_DIR_CHECKOUT}/${env.TARBALL_GIT_NAME} -C ${LOCAL_DIR_CHECKOUT}

            #----------------

            echo '📂 EFS workspace contents: (v1)'
            ls -al ${params.EFS_LIFERAY_ARTIFACT_REPOS}
            ls -al ${params.EFS_LIFERAY_ARTIFACT_REPOS}/${TARBALL_GIT_NAME}



            cp ${params.EFS_LIFERAY_ARTIFACT_BUNDLES}/${env.TARBALL_GIT_NAME} ${LOCAL_DIR_CHECKOUT}


            ls -al ${LOCAL_DIR_CHECKOUT}
            echo '📦 Extracting tarball (with pigz)...'
            tar         -xzf ${LOCAL_DIR_CHECKOUT}/${env.TARBALL_GIT_NAME} -C ${LOCAL_DIR_CHECKOUT}


            echo '📂 Extracted contents:  '
            ls -al ${LOCAL_DIR_CHECKOUT}
            echo '📂 Checking out source code (emulated) done...'
            rm -f ${LOCAL_DIR_CHECKOUT}/${env.TARBALL_GIT_NAME}
            echo '📂 Source code ready in ${LOCAL_DIR_CHECKOUT}'
            
          """

        }
      }
    }

  

  stage('Test3 - Step 0 (ant setup-profile-dxp)') {

      steps {
        container('runner') {

          // dir("${LOCAL_DIR_CHECKOUT}/liferay-portal") {

            script {
                sh """
                  echo '📥 Build the Bundle - Step 0 ... '
                  echo "📂 LOCAL_DIR_CHECKOUT: ${LOCAL_DIR_CHECKOUT}  "   
                  ls -a
                  pwd     

                  cd /opt/dev/projects/github/liferay-portal



                  echo "app.server.parent.dir=/opt/dev/projects/github/liferay-portal/bundles" > app.server.\$HOSTNAME.properties

                  echo "liferay.home=/opt/dev/projects/github/liferay-portal/bundles" > build.\$HOSTNAME.properties
                  echo "mirrors.hostname=" >> build.\$HOSTNAME.properties
                  
                  #
                  # NOTE: These properties are variable between different testing environments
                  #

                  echo "java.jdk.default.runtime.version=jdk21" > test.\$HOSTNAME.properties
                  echo "database.type=postgresql" >> test.\$HOSTNAME.properties
                  echo "database.postgresql.host=postgresql" >> test.\$HOSTNAME.properties
                  echo "database.postgresql.username=root" >> test.\$HOSTNAME.properties
                  echo "database.postgresql.password=liferay123" >> test.\$HOSTNAME.properties

                  ant setup-profile-dxp
                  
                  ant -f build-test.xml rebuild-database prepare-portal-ext-properties


                """ 
            }

         // }


        }
      }
    }



    stage('Test1 (ant -f build-test-batch.xml dist-jdk7)') {

      steps {
        container('runner') {

          // dir("${LOCAL_DIR_CHECKOUT}/liferay-portal") {


            script {
                sh """
                  echo '📥 Build the Bundle - Step 1 ... '
                  echo "📂 LOCAL_DIR_CHECKOUT: ${LOCAL_DIR_CHECKOUT}  "   
                  ls -a
                  pwd     

                  cd /opt/dev/projects/github/liferay-portal


                  ant -f build-test-batch.xml modules-integration-postgresql163 -Dtest.batch.name=modules-integration-postgresql163 -Daxis.variable=0 -DTEST_CLASS_GROUP_0=com/liferay/jenkins/results/parser/test/DummyIntegrationTest.class
                  
                  #
                  # This portion of the script uploads the Test Results artifacts to S3 to be used to be report
                  #

                  # aws s3 cp --no-progress \
                  #         /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml \
                  #         s3://liferayci-file-propagator-mvp/builds/1/modules-integration-postgresql163/TESTS-TestSuites.xml

                """ 
            }

         // }


        }
      }
    }



    stage('Complete') {
      steps {
        echo "✅ ${DOWNSTREAM_BUILD_ID} completed successfully!"
      }
    }
  }
  
}