/**
  * Jenkinsfile 
  * - Worker Node Working Ok
  *
  * - This versio does the checkout of the liferay-portal repo in 47 seconds
  *
  *
  * Status: ✅ Minimal pod scheduled successfully
  */
@Library('Liferay-Global-Shared-Libs') _

import com.liferay.TestBuild

pipeline {



  agent {
    kubernetes {
      label 'liferay-agent-test'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::300374333822:role/jenkins-irsa-role
spec:
  serviceAccountName: jenkins-agent
  securityContext:
    fsGroup: 1000
  labels:
    jenkins: agent

  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace



    - name: aws-liferay-runner
      image: 300374333822.dkr.ecr.us-east-2.amazonaws.com/aws-liferay-runner:2.0.1
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /home/jenkins/agent
          name: efs-workspace
        - mountPath: /home/jenkins/local
          name: workspace-volume
  
  volumes:
    - name: efs-workspace
      persistentVolumeClaim:
        claimName: jenkins-efs-pvc
    - name: workspace-volume
      emptyDir: {}

  nodeSelector:
    jenkins-role: agent
  tolerations:
    - key: "jenkins-role"
      operator: "Equal"
      value: "agent"
      effect: "NoSchedule"

"""
    }
  }

  options {
    skipDefaultCheckout()
  }




  environment {

    GIT_REPO_URL = 'https://github.com/pablo-inchausti-caylent/liferay-portal.git'
    GIT_BRANCH   = 'master-ci-6005-postgresql'

    AWS_ACCOUNT_ID='300374333822'
    AWS_REGION='us-east-2'

    AWS_S3_BUCKET='liferayci-file-propagator-mvp'
    AWS_S3_PATH='build'


    // CUSTOM_BUILD_NUMBER = "${env.BUILD_NUMBER}"
    CUSTOM_BUILD_NUMBER = "1"

    AWS_S3_URL_ARTIFACTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.CUSTOM_BUILD_NUMBER}/artifacts"
    AWS_S3_URL_TESTS="s3://${AWS_S3_BUCKET}/${AWS_S3_PATH}/${env.CUSTOM_BUILD_NUMBER}/tests"

    BUILD_BUNDLE_NAME='liferay-portal-bundle-tomcat.tar.gz'
    BUILD_SOURCE_NAME='liferay-portal-source.tar.gz'



    // s3://liferayci-file-propagator-mvp/build/35/artifacts
    // s3://liferayci-file-propagator-mvp/build/35/tests

    // liferay-portal-bundle-tomcat.tar.gz  (~1.7gb)
    // liferay-portal-source.tar.gz         (~1.2gb)

    LOCAL_DIR_CHECKOUT  = "/opt/dev/projects/github"
    TARBALL_GIT_NAME_PL = "liferay-portal-repo-${env.CUSTOM_BUILD_NUMBER}.tar.gz"
    TARBALL_GIT_REPO_PL = "${LOCAL_DIR_CHECKOUT}/${TARBALL_GIT_NAME_PL}"

    TARBALL_GIT_NAME_EE = "liferay-jenkins-ee-repo-${env.CUSTOM_BUILD_NUMBER}.tar.gz"
    TARBALL_GIT_REPO_EE = "${LOCAL_DIR_CHECKOUT}/${TARBALL_GIT_NAME_EE}"

    EFS_MOUNT_PATH                = "/home/jenkins/agent"
    EFS_LIFERAY_ARTIFACT_FOLDER   = "${EFS_MOUNT_PATH}/liferay-artifacts/build-${env.CUSTOM_BUILD_NUMBER}"
    EFS_LIFERAY_ARTIFACT_REPOS    = "${EFS_LIFERAY_ARTIFACT_FOLDER}/repo-github"
    EFS_LIFERAY_ARTIFACT_BUNDLES  = "${EFS_LIFERAY_ARTIFACT_FOLDER}/bundles"
    EFS_LIFERAY_ARTIFACT_TEST     = "${EFS_LIFERAY_ARTIFACT_FOLDER}/tests"

    DO_LIFERAY_PORTAL_CHECKOUT      = 'do_liferay-portal-Checkout'
    DO_LIFERAY_PORTAL_EFS           = 'do_liferay-portal-EFS'
    CHOICE_LIFERAY_PORTAL           = "FALSE ${DO_LIFERAY_PORTAL_CHECKOUT}"

    DO_LIFERAY_JENKINS_EE_CHECKOUT  = 'do_liferay-jenkins-ee-Checkout'
    DO_LIFERAY_JENKINS_EE_EFS       = 'do_liferay-jenkins-ee-EFS'
    CHOICE_LIFERAY_JENKINS_EE       = "${DO_LIFERAY_JENKINS_EE_EFS}"

  }


  stages {
    


    stage('Print Environment') {
      steps {
        script {


          echo """
          Environment Variables:
          Branch      : ${env.BRANCH_NAME}
          Job Name    : ${env.JOB_NAME}
          Build Number: ${env.CUSTOM_BUILD_NUMBER}
          Workspace   : ${env.WORKSPACE}
          Node Name   : ${env.NODE_NAME}
          """
          
          log.info('Validation Shared Libs Integration')
          log.warning('Liferay-Global-Shared-Libs is working fine')

          echo "kubectl exec -it ${env.NODE_NAME} -c runner -n liferay-jenkins -- bash"
       
       
        }


      }
    }



    stage('Checkout liferay-portal') {
      when {
        expression { return env.CHOICE_LIFERAY_PORTAL == DO_LIFERAY_PORTAL_CHECKOUT }
      }
      steps {

        container('aws-liferay-runner') {

          
            script {
        
              echo "📂 Checkout :: LOCAL_DIR_CHECKOUT: ${LOCAL_DIR_CHECKOUT}"
              echo "📦 Checkout :: TARBALL_GIT_REPO_PL: ${TARBALL_GIT_REPO_PL}"

              // Clean the target folder
              sh """
                echo '🧹 Version 4...'
                echo '🧹 Cleaning checkout folder...'
                rm -rf ${LOCAL_DIR_CHECKOUT} && mkdir -p ${LOCAL_DIR_CHECKOUT}
              """

            // input message: 'Proceed with Checkout? (v1)', ok: 'Yes, proceed'

              withCredentials([
                usernamePassword(
                  credentialsId: 'github-pat-pei',
                  usernameVariable: 'GIT_USERNAME',
                  passwordVariable: 'GIT_PASSWORD'
                )
              ]) {
                sh """
                  echo '📥 Manual clone in container context...'
                  git clone --depth=1 \
                            --branch ${env.GIT_BRANCH} \
                      https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/pablo-inchausti-caylent/liferay-portal.git \
                      ${LOCAL_DIR_CHECKOUT}/liferay-portal
                """

                      //  ${LOCAL_DIR_CHECKOUT}/liferay-portal
                // env.GIT_COMMIT = sh(script: "git rev-parse HEAD", returnStdout: true).trim()
              }
  
            }
          

          }
        }

    }



    stage('EFS liferay-jenkins-ee') {
      when {
        expression { return env.CHOICE_LIFERAY_JENKINS_EE == DO_LIFERAY_JENKINS_EE_EFS }
      }
      steps {
        container('aws-liferay-runner') {
          script {
              sh """
                echo '📥 Doing EFS liferay-jenkins-ee ... '
              """
       
            echo "📂 LOCAL_DIR_CHECKOUT: ${LOCAL_DIR_CHECKOUT}"
            echo "📦 TARBALL_GIT_REPO_EE: ${TARBALL_GIT_REPO_EE}"

            // sshagent(['GitHub-ssh-pei']) {
            //     sh """
            //       git clone --depth=1 \
            //                 --branch master \
            //                 git@github.com/liferay/liferay-jenkins-ee.git \
            //                 ${LOCAL_DIR_CHECKOUT} 
            //     """
            // }
            
            sh """
              echo '📂 EFS workspace and local contents:'
              ls -al ${LOCAL_DIR_CHECKOUT}
              ls -al ${EFS_LIFERAY_ARTIFACT_REPOS}

              echo '📂 EFS workspace copy liferay-jenkins-ee to local'
              cp ${EFS_LIFERAY_ARTIFACT_REPOS}/${TARBALL_GIT_NAME_EE} ${LOCAL_DIR_CHECKOUT}
              
              echo '📦 Extracting tarball (with pigz)...'
              tar -I pigz -xf ${LOCAL_DIR_CHECKOUT}/${TARBALL_GIT_NAME_EE} -C ${LOCAL_DIR_CHECKOUT}
              
              echo '📂 Remove tar.gz ...'
              rm -f ${LOCAL_DIR_CHECKOUT}/${TARBALL_GIT_NAME_PL}

              echo '📂 New Extracted contents:  '
              ls -al ${LOCAL_DIR_CHECKOUT}
            """ 
          }
        }






        }
      }
    }
  




  }


  post {
    always {
      input message: 'Finish the pipeline?', ok: 'Yes, proceed'
      echo "🔚 Pipeline completed. Cleaning up workspace..."
    
    }
  }


}