@Library('Liferay-Shared-Libs') _

pipeline {

  agent any

  options {
    skipDefaultCheckout()
  }

  stages {

    stage('Print Environment - v5') {
      steps {
        script {


          echo "Testing Shared Libs"

          log.info 'Starting'
          log.warning 'Nothing to do!'


          echo "Branch: ${env.BRANCH_NAME}"
          echo "Job Name: ${env.JOB_NAME}"
          echo "Build Number: ${env.BUILD_NUMBER}"
          echo "Workspace: ${env.WORKSPACE}"
          echo "Git Commit: ${env.GIT_COMMIT}"
        }
        // Or print everything
        sh 'printenv'
      }
    }

    

     stage('Checkout Shallow') {
      steps {
        // container('runner') {
        //   checkout([
        //     $class: 'GitSCM',
        //     branches: [[name: "*/${env.GIT_BRANCH}"]],
        //     userRemoteConfigs: [[
        //       url: "${env.GIT_REPO_URL}",
        //       credentialsId: 'github-pat-pei'
        //     ]],
        //     extensions: [
        //       [$class: 'CloneOption', shallow: true, depth: 1, noTags: false, reference: '', timeout: 10]
        //     ]
        //   ])
        // }

          sh '''

            echo "🔍 Checking EFS mount at /home/jenkins/agent"
            mount | grep /home/jenkins/agent || echo "❌ EFS NOT mounted"

            date > /home/jenkins/agent/git-repo-emulation-gz.txt
            echo "📄 GitRepo emulation ." >> /home/jenkins/agent/git-repo-emulation-gz.txt

            ls -al /home/jenkins/agent
          '''
        
      }
    }


    stage('Decide What to Run') {
      steps {
        script {
            def changedFiles = sh(script: "git diff --name-only HEAD~1", 
                            returnStdout: true).trim().split("\n")

            def buildFolder      = 'MVP-Downstream-Builds'         // Build folder in Jenkins UI
            def homeDir          = 'ci-mvp-downstream-builds'      // Home directory in Jenkins Agent
            def topLevelBranch   = 'master-ci-6005-postgresql'
            def downStreamBranch = 'master-ci-6005-downstream-builds'

            def nameBuilds   = ["MVP Liferay Blueprint/${topLevelBranch}",
                                "${buildFolder}/MVP-Downstream-Build-1/${downStreamBranch}", 
                                "${buildFolder}/MVP-Downstream-Build-2/${downStreamBranch}", 
                                "${buildFolder}/MVP-Downstream-Build-3/${downStreamBranch}"]

            echo "wip Triggering downstream job"

            // def dirBuilds   = ["${homeDir}/top-level-build/", 
            //                    "${homeDir}/downstream-build-1", 
            //                    "${homeDir}/downstream-build-2",
            //                    "${homeDir}/downstream-build-3"]

            def dirBuilds   = [ "${homeDir}/top-level-build/" ]

            for (int i = 0; i < dirBuilds.size(); i++) {
                
                def dirBuild  = dirBuilds[i]
                def nameBuild = nameBuilds[i]

                if (changedFiles.any { it.startsWith( dirBuild  ) }) {
                    build job: "${nameBuild}"
                    echo "👉 Triggering downstream job: ${nameBuild}" 
                }
            }

        }
      }
    }
  }
}


