env:
    AUTHORIZED_OWNERS: brianchandotcom

jobs:
    close-merge-conflicts:
        if: contains(env.AUTHORIZED_OWNERS, github.repository_owner)
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        permissions:
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    set -e

                    function main {
                        local authorized_owner
                        local authorized=false

                        for authorized_owner in ${AUTHORIZED_OWNERS}
                        do
                            if [[ "${authorized_owner}" == "${{ github.repository_owner }}" ]]
                            then
                                authorized=true

                                break
                            fi
                        done

                        if [[ "${authorized}" == "false" ]]
                        then
                            echo "${{ github.repository_owner }} is not authorized."

                            exit 0
                        fi

                        local pr_number=${{ github.event.pull_request.number }}
                        local pr_url=${{ github.event.pull_request.html_url }}

                        echo "Checking pull request #${pr_number} in ${{ github.repository_owner }}/${{ github.event.repository.name }}..."

                        local pr_details_json=$( \
                            curl \
                                --header "Authorization: Bearer ${GITHUB_TOKEN}" \
                                --silent \
                                "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${pr_number}")

                        local mergeable_state=$( \
                            echo "${pr_details_json}" | \
                            jq \
                                --raw-output \
                                ".mergeable_state")

                        local max_retries=6
                        local retry_count=0

                        while [[ "${mergeable_state}" == "unknown" || "${mergeable_state}" == "null" ]] &&
                              [[ "${retry_count}" -lt "${max_retries}" ]]
                        do
                            echo "Pull request ${pr_url} state is unknown."
                            echo "Waiting 5s (Attempt $((retry_count + 1)) of ${max_retries})..."

                            sleep 5

                            pr_details_json=$( \
                                curl \
                                    --header "Authorization: Bearer ${GITHUB_TOKEN}" \
                                    --silent \
                                    "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${pr_number}")

                            mergeable_state=$( \
                                echo "${pr_details_json}" | \
                                jq \
                                    --raw-output \
                                    ".mergeable_state")

                            retry_count=$(expr "${retry_count}" + 1)
                        done

                        if [[ "${mergeable_state}" == "dirty" ]]
                        then
                            echo "Closing pull request: ${pr_url} due to conflicts."

                            curl \
                                --data "{\"body\": \"This pull request has merge conflicts and has been closed. Please resolve conflicts and re-send.\"}" \
                                --header "Authorization: Bearer ${GITHUB_TOKEN}" \
                                --output /dev/null \
                                --request POST \
                                --silent \
                                "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${pr_number}/comments"

                            curl \
                                --data "{\"state\": \"closed\"}" \
                                --header "Authorization: Bearer ${GITHUB_TOKEN}" \
                                --output /dev/null \
                                --request PATCH \
                                --silent \
                                "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/pulls/${pr_number}"
                        else
                            echo "Pull request #${pr_number} is mergeable or state is ${mergeable_state}. No action taken."
                        fi
                    }

                    main
on:
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch: